services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/settings.json:/usr/share/elasticsearch/config/settings.json:ro
      - ./elasticsearch/mappings.json:/usr/share/elasticsearch/config/mappings.json:ro
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kibana:
    image: kibana:8.11.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ElasticSearch__Url=http://elasticsearch:9200
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic-net
    volumes:
      - ./data.csv:/app/data.csv:ro
      - ./elasticsearch:/app/elasticsearch:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic-net:
    driver: bridge